# Generated by Django 4.0.2 on 2022-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=30, max_length=50),
            preserve_default=False,
        ),
    ]
